[package]
name = "plegine_derive"
version = "0.1.0"
edition = "2021"


[dependencies]
plegine = { version = "0.1", path = "../plegine" }
proc-macro2 = "1.0"
syn = "1.0"
quote = "1.0"

[lib]
name = "plegine_derive"
proc-macro = true
